### ISSUE TITLE
Resolve error of netlify build 

### ISSUE THREAD

**Issue by G-Sudarshan** [Eaglion-Programmers/Eaglion-Programmers.github.io#20]
After adding footer component from @MadhukrishnaNipankar we are getting some error in build command for netlify, @thisisbillall please look into this. I think there is some simple typo which needs to be removed.

**Comment by G-Sudarshan** [comment]
@thisisbillall Just change code build will be triggered automatically

**Comment by thisisbillall** [comment]
Dont mind navbar is under development now!!

**Comment by G-Sudarshan** [comment]
Great troubleshooting @thisisbillall💯
