### ISSUE TITLE
Community Members Page

### ISSUE THREAD

**Issue by Sanika2103** [Eaglion-Programmers/Eaglion-Programmers.github.io#23]
Design page for displaying community members
1. Add photos of all members
2.  Linkedin IDs can be added too.
3. Responsive cards can be designed for each member
4.  Images of all members are uploaded  in frontend > Public > Images > Community-Members-Images

You may implement your own ideas too.

**Comment by G-Sudarshan** [comment]
> Can you please assign it to me?

Evryone has to upload thier own photos

**Comment by G-Sudarshan** [comment]
yes @MadhukrishnaNipankar its assigned to you.....

> can i be assigned with creating json file @G-Sudarshan ?
