### ISSUE TITLE
Design about page

### ISSUE THREAD

**Issue by Sanika2103** [Eaglion-Programmers/Eaglion-Programmers.github.io#25]
Design about page containing
1.  Information about community
2.  Motive of community 
 
You may add your own ideas too.

**Comment by MadhukrishnaNipankar** [comment]
@Sanika2103 I can do It

**Comment by Sanika2103** [comment]
Yeah, take your time. Comment when you're done with it.

**Comment by MadhukrishnaNipankar** [comment]
@Sanika2103  Would you be able describe more about it ?

**Comment by Sanika2103** [comment]
Okay. Take your time.

**Comment by MadhukrishnaNipankar** [comment]
@thisisbillall  are you looking to the managers cards....i told u for ?
