### ISSUE TITLE
Display all members of community with their photo and social media links

### ISSUE THREAD

**Issue by G-Sudarshan** [Eaglion-Programmers/Eaglion-Programmers.github.io#29]
First of all we need to fix some format like json or you can give your own idea, will first discuss here and then finalize format

**Comment by gayatri2** [comment]
Sounds good! 
The card design would be similar to the 'members' cards?

**Comment by G-Sudarshan** [comment]
Yes

**Comment by thisisbillall** [comment]
@G-Sudarshan   I have already created those cards and JSON array for that but i am lacking due to "LESS DATA" firstly ask everyone to update their data asap !!

**Comment by G-Sudarshan** [comment]
ok can you share example json object here do image is there too in json object?

**Comment by thisisbillall** [comment]
yes ill share that

**Comment by thisisbillall** [comment]
the same array of json obj i had used for CARDS we just need to put it into separates JSON file

**Comment by G-Sudarshan** [comment]
@thisisbillall Whats the location of this json file in project?

**Comment by thisisbillall** [comment]
@G-Sudarshan  https://github.com/Eaglion-Programmers/Eaglion-Programmers.github.io/blob/main/frontend/src/Components/Members.js

**Comment by G-Sudarshan** [comment]
> @G-Sudarshan https://github.com/Eaglion-Programmers/Eaglion-Programmers.github.io/blob/main/frontend/src/Components/Members.js
> 
> this is not a json fiile but array we can make file
if there would be json file people cant mess up with other code thats why I was suggesting json file..... what you say @thisisbillall .....

**Comment by gayatri2** [comment]
Sure, 

> > so basically, I've to take the data from JSON and render it on cards right?
> > 💯Exactly

Sure, I am working on it!

**Comment by G-Sudarshan** [comment]
Excellent contribution @gayatri2 🚀
