### ISSUE TITLE
Resolve conflict due too previous committ

### ISSUE THREAD

**Issue by G-Sudarshan** [Eaglion-Programmers/Eaglion-Programmers.github.io#33]
There is error occuring in netlify due to previous commit

**Comment by G-Sudarshan** [comment]
<img width="1440" alt="Screenshot 2021-10-19 at 3 22 10 PM" src="https://user-images.githubusercontent.com/43257931/137886865-cd4d48cf-13b5-406b-a672-6373d1263b73.png">

**Comment by MadhukrishnaNipankar** [comment]
@G-Sudarshan  Conflict Resolved !
